### ISSUE TITLE
Headless login does not work under macOS 10.15

### ISSUE THREAD

**Issue by PSiAU** [piontas/python-aada#12]
Firstly I want to say thanks for writing this awesome tool :)

Now for the bug report:
The login process bombs out under macOS Catalina with the following error.
```
[E:pyppeteer.connection] connection unexpectedly closed
Task exception was never retrieved
future: <Task finished coro=<Connection._async_send() done, defined at /Users/xxxxxxx/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pyppeteer/connection.py:69> exception=InvalidStateError('invalid state')>
```

Non headless mode logs in just fine.

**Comment by piontas** [comment]
it works fine in MacOS. Try installing/updating from latest master branch.
