### ISSUE TITLE
Random login error when using PhoneAppNotification

### ISSUE THREAD

**Issue by boriel** [piontas/python-aada#8]
Occasionally, when login in using `PhoneAppNotification` (don't know of others), I get the following error:

```Azure username: josemanuel.rodriguez@XXXXXXX.com
Azure password: 
Processing MFA authentication...
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.',)>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
An error occured while authenticating, check credentials.
```

This happens after I approve the login in my mobile phone, so I guess it should not be caused by a mistyped password (?)
Any suggestion on this?
Also, thanks for this project 😃

**Comment by piontas** [comment]
I will have a look and let you know, meanwhile try with `-n` flag to see what is happening

**Comment by piontas** [comment]
This is now fixed.
