### ISSUE TITLE
WARNING: Generating metadata for package python-aada produced metadata for project name aada. Fix your #egg=python-aada fragments.

### ISSUE THREAD

**Issue by jbeninson** [piontas/python-aada#9]
Hi, I am getting the following output when installing as per directions on the README. I am using virtualenv with a homebrew installed python3.7. The following is the output: 

[python-aada-install-error.txt](https://github.com/piontas/python-aada/files/3585963/python-aada-install-error.txt)

**Comment by piontas** [comment]
What version of `pip` are you using?
Try to run `pip install pip -U` before you install `aada`

**Comment by piontas** [comment]
This issue is fixed now.
